# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jwclientreact

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  simplebuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    
    - name: Send mail
      if: ${{ success() }}
      uses: dawidd6/action-send-mail@v2
      with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Status budowy aplikacji React
          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}
          body: Build zakończony powodzeniem!
  build:
    runs-on: 'ubuntu-latest'
    needs: simplebuild
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7e64c0d361c44b7184d5c797e3b40c02 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ffe1a190b1c1424997f89951f0c6a3dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7e64c0d361c44b7184d5c797e3b40c02 }}/reactazure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jwclientreact'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_df1a5563198142c9893aca6e6f6c451b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7e64c0d361c44b7184d5c797e3b40c02 }}/reactazure:${{ github.sha }}'
